name: Auto Increment Release

on:
  push:
    branches:
      - 'master'
      - 'release'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Fetch Release Info
        id: get_release
        run: |
          # Fetch all tags
          git fetch --tags
          
          # Get the latest tag (if available)
          latest_tag=$(git tag --list | sort -V | tail -n 1)
          
          if [ -z "$latest_tag" ]; then
            echo "No tags found, defaulting to v1.0.0"
            latest_tag="v1.0.0"
          else
            echo "Latest tag found: $latest_tag"
          fi
          
          # Increment version (bump patch version)
          version=$(echo $latest_tag | sed 's/^v//' | awk -F. '{ printf("v%d.%d.%d", $1, $2, $3+1) }')
          echo "Next version: $version"
          echo "version=$version" >> $GITHUB_ENV

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        with:
          tag_name: ${{ env.version }}
          release_name: ${{ env.version }}
          body: |
            A new release has been created for version ${{ env.version }}.
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}